### PR TITLE
fix: handles already-released PFCP sessions

### LINKED ISSUE #1003: [Bugs] SMF returns 500 on /release when crafted NGAP/NAS PDU release/re-establish flow desynchronizes PFCP session state
## Bug Description
A carefully crafted but still decodable NGAP/NAS registration + PDU session establishment + release + follow-up request sequence can drive free5GC into an SMF internal error path.
With a specially constructed message flow, the UE is able to:
1. complete normal registration
2. create an SM context successfully
3. trigger PDU session release
4. immediately send a follow-up UL NAS request that re-enters the same SM context handling path
Under this sequence, SMF and PFCP session state become inconsistent during the `/release` path.  
SMF sends a PFCP Session Deletion Request, but UPF responds with an unexpected SEID situation and logs:
- `handleSessionDeletionRequest: Sess: sess not found`
- `received unexpected SEID response message`
After that, SMF returns:
- `POST /nsmf-pdusession/v1/sm-contexts/.../release -> 500`

This is an internal server-side error triggered by a crafted but protocol-decodable message flow.  
The failure should be handled gracefully instead of surfacing as an SMF 500 on the release path.

## To Reproduce

1. Start free5GC normally.
2. Use the following two files for reproduction:
sender script:
[smf_release_500_minimal_sender.py](https://github.com/user-attachments/files/26609827/smf_release_500_minimal_sender.py)
seed file:
[smf_release_500_minimal_seed.json](https://github.com/user-attachments/files/26609836/smf_release_500_minimal_seed.json)
3. Install required dependencies:
pip install pycryptodome
pip install pycrate
pip install pysctp
4. Run:
python smf_release_500_minimal_sender.py --seed-file smf_release_500_minimal_seed.json

## Expected Behavior
Even when receiving a carefully crafted or abnormal-but-decodable NGAP/NAS message sequence, free5GC should handle SM context release safely.
PFCP session deletion inconsistency should not cause SMF to return an internal 500 on:
/nsmf-pdusession/v1/sm-contexts/.../release
SMF should reject or clean up the session in a controlled way.

## Screenshots
Image

## Environment
free5GC Version: v4.2.1]
OS: Ubuntu 22.04
Kernel version: normal
go version: normal
C compiler version (optional): normal

### Configuration Files
Smf normal config.

### PCAP File
[smfrelease.zip](https://github.com/user-attachments/files/26609891/smfrelease.zip)

### Log File
[log.txt](https://github.com/user-attachments/files/26609895/log.txt)

### PR DESCRIPTION
**Pull request by DBGR18**
fix [issue#1003](https://github.com/free5gc/free5gc/issues/1003)

This pull request introduces a mechanism to prevent redundant PFCP session release operations by tracking the release status within the `SMContext`. The main change is the addition of a `PFCPReleaseDone` flag, which ensures that PFCP session release logic is only executed once per context, improving the robustness and efficiency of session management.

**Session Release Idempotency Improvements:**
* Added a `PFCPReleaseDone` boolean field to the `SMContext` struct to track whether the PFCP session has already been released, preventing duplicate release attempts.
* Updated `HandlePDUSessionSMContextRelease` and `HandlePDUSessionSMContextLocalRelease` to check `PFCPReleaseDone` before attempting to release the PFCP session, logging and skipping the release if it has already been performed. 

**Session Release Logic Updates:**
* Modified the `releaseSession` function to set `PFCPReleaseDone` to `false` at the start and to `true` upon successful session release, ensuring accurate tracking of the release status.

### CODE REVIEW

**Comment by roundspring2003** [comment]
@Alonza0314 test all pass

File: internal/sbi/processor/pdu_session.go [hunk 1]
```diff
@@ -1246,10 +1246,13 @@ func (p *Processor) HandlePDUSessionSMContextRelease(
 		}
 	}
 
-	if !smContext.CheckState(smf_context.InActive) {
-		smContext.SetState(smf_context.PFCPModification)
+	var pfcpResponseStatus smf_context.PFCPSessionResponseStatus
+	if smContext.PFCPReleaseDone {
```
Comment (Alonza0314) [inline internal/sbi/processor/pdu_session.go:1250]: Can‘t we just using smContext State to check if PFCP session active or not？Why we need an additional `PFCPReleaseDone` variable？

**Review by Alonza0314 — APPROVED** [review]
