### PR TITLE
fix: ULCL not working; close #141

### LINKED ISSUE #141: ULCL not working
Hi @free5gc-org

Since the commit shown below, ULCL doesn't seem to work.

https://github.com/free5gc/smf/commit/00e4b4e06bf44688f64f6a6f456c675b32643b9b

In the one-previous commit version, ULCL works.

Could you please check that there?

### PR DESCRIPTION
**Pull request by louisroyer**

### CODE REVIEW

**Comment by ianchen0119** [comment]
@lyz508 
Please help to review the PR.

Thanks!

File: internal/context/sm_context.go [hunk 1]
```diff
@@ -587,7 +605,7 @@ func (c *SMContext) SelectDefaultDataPath() error {
 		c.Log.Infof("Has pre-config default path")
 		uePreConfigPaths := GetUEPreConfigPaths(c.Supi, c.SelectedUPF.Name)
 		for _, dp := range uePreConfigPaths.DataPathPool {
-			if !dp.IsDefaultPath {
+			if dp.IsDefaultPath {
```
Comment (lyz508) [inline internal/context/sm_context.go:608]: Hi, @louisroyer,
If we add the default path created by the ULCL config here,
SMF will create a PDR without a decision from the PCF (e.g., additional charging URRs).
Maybe we could directly use the default path created by PCC rules?

Comment (louisroyer) [reply internal/context/sm_context.go:608]: Hi @lyz508,
how can we use this path? According to https://github.com/free5gc/smf/blob/9ab42f194d243a13e60f8b29a782fb5a6e68aa2b/internal/sbi/processor/pdu_session.go#L228 `SelectDefaultDataPath` is called to create the default datapath when it is not found…

Comment (lyz508) [reply internal/context/sm_context.go:608]: Hi, @louisroyer,
Sorry for the late reply.
Maybe we could add a check before adding the ULCL default path to SMContext?
```go=
defaultPath = uePreConfigPaths.DataPathPool.GetDefaultPath()
if c.Tunnel.DataPathPool.GetDefaultPath() == nil {
    c.Tunnel.AddDataPath(defaultPath)
}
```
Since the default path is added to SMContext when handling PCCRules creation, this approach would help prevent duplicate creation of the default path.
https://github.com/free5gc/smf/blob/9ab42f194d243a13e60f8b29a782fb5a6e68aa2b/internal/context/sm_context.go#L649

Comment (louisroyer) [reply internal/context/sm_context.go]: @lyz508 Is eab6e3c77841068023ab8317be7b87d7b766161a what you had in mind ?

Comment (lyz508) [reply internal/context/sm_context.go]: @louisroyer Yes, thanks for the update!

**Comment by lyz508** [comment]
@ianchen0119 LGTM.
I also tested the ULCL and charging functionality, and they work fine.

**Comment by ianchen0119** [comment]
Hi @Alonza0314 

Please test the PR on next branch by using CI-TEST.

Thanks.

**Comment by Alonza0314** [comment]
> Hi @Alonza0314
> 
> Please test the PR on next branch by using CI-TEST.
> 
> Thanks.

It passed the tests. 🎉
